language: python
python:
# geeknote uses features of python not present in 2.6
#  - "2.6"
  - "2.7"
# The official Evernote SDK doesn't support Python 3 yet
# Keep an eye on https://github.com/evernote/evernote-sdk-python3
#  - "3.2"
#  - "3.3"
#  - "3.4"
#  - "3.5"
#  - "3.5-dev" # 3.5 development branch
#  - "nightly" # currently points to 3.6-dev

before_install:
  - date "+%Y %m %d %H %M %S"

before_script:
  - date "+%Y %m %d %H %M %S"

os:
  - linux
#  - osx

install:
  - pip install -r requirements.txt

# command to run tests
script: python -m pytest -s
